name: Scheduled Tasks

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every day at midnight

jobs:
  scheduled_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Scheduled Tasks
      run: npm run scheduled-tasks

